apiVersion: v1
kind: Service
metadata:
  name: docmind-api
spec:
  selector:
    app: docmind-api
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: docmind-ui
spec:
  selector:
    app: docmind-ui
  ports:
    - port: 8501
      targetPort: 8501
  type: ClusterIP
